export const cardData = {
  "majorArcana": [
    { name: "The Fool", value: 0, file: "00-thefool.jpg" },
    { name: "The Magician", value: 1, file: "01-themagician.jpg" },
    { name: "The High Priestess", value: 2, file: "02-thehighpriestess.jpg" },
    { name: "The Empress", value: 3, file: "03-theempress.jpg" },
    { name: "The Emperor", value: 4, file: "04-theemperor.jpg" },
    { name: "The Hierophant", value: 5, file: "05-thehierophant.jpg" },
    { name: "The Lovers", value: 6, file: "06-thelovers.jpg" },
    { name: "The Chariot", value: 7, file: "07-thechariot.jpg" },
    { name: "Strength", value: 8, file: "08-strength.jpg" },
    { name: "The Hermit", value: 9, file: "09-thehermit.jpg" },
    { name: "Wheel of Fortune", value: 10, file: "10-wheeloffortune.jpg" },
    { name: "Justice", value: 11, file: "11-justice.jpg" },
    { name: "The Hanged Man", value: 12, file: "12-thehangedman.jpg" },
    { name: "Death", value: 13, file: "13-death.jpg" },
    { name: "Temperance", value: 14, file: "14-temperance.jpg" },
    { name: "The Devil", value: 15, file: "15-thedevil.jpg" },
    { name: "The Tower", value: 16, file: "16-thetower.jpg" },
    { name: "The Star", value: 17, file: "17-thestar.jpg" },
    { name: "The Moon", value: 18, file: "18-themoon.jpg" },
    { name: "The Sun", value: 19, file: "19-thesun.jpg" },
    { name: "Judgement", value: 20, file: "20-judgement.jpg" },
    { name: "The World", value: 21, file: "21-theworld.jpg" }
  ],
  // 1 = Ace, 11 = Page, 12 = Knight, 13 = Queen, 14 = King
  "Wands": [
    { 1: "wands01.jpg" },
    { 2: "wands02.jpg" },
    { 3: "wands03.jpg" },
    { 4: "wands04.jpg" },
    { 5: "wands05.jpg" },
    { 6: "wands06.jpg" },
    { 7: "wands07.jpg" },
    { 8: "wands08.jpg" },
    { 9: "wands09.jpg" },
    { 10: "wands10.jpg" },
    { 11: "wands11.jpg" },
    { 12: "wands12.jpg" },
    { 13: "wands13.jpg" },
    { 14: "wands14.jpg" },
  ],
  "Cups": [
    { 1: "cups01.jpg" },
    { 2: "cups02.jpg" },
    { 3: "cups03.jpg" },
    { 4: "cups04.jpg" },
    { 5: "cups05.jpg" },
    { 6: "cups06.jpg" },
    { 7: "cups07.jpg" },
    { 8: "cups08.jpg" },
    { 9: "cups09.jpg" },
    { 10: "cups10.jpg" },
    { 11: "cups11.jpg" },
    { 12: "cups12.jpg" },
    { 13: "cups13.jpg" },
    { 14: "cups14.jpg" }
  ],
  "Swords": [
    { 1: "swords01.jpg" },
    { 2: "swords02.jpg" },
    { 3: "swords03.jpg" },
    { 4: "swords04.jpg" },
    { 5: "swords05.jpg" },
    { 6: "swords06.jpg" },
    { 7: "swords07.jpg" },
    { 8: "swords08.jpg" },
    { 9: "swords09.jpg" },
    { 10: "swords10.jpg" },
    { 11: "swords11.jpg" },
    { 12: "swords12.jpg" },
    { 13: "swords13.jpg" },
    { 14: "swords14.jpg" }
  ],
  "Pentacles": [
    { 1: "pentacles01.jpg" },
    { 2: "pentacles02.jpg" },
    { 3: "pentacles03.jpg" },
    { 4: "pentacles04.jpg" },
    { 5: "pentacles05.jpg" },
    { 6: "pentacles06.jpg" },
    { 7: "pentacles07.jpg" },
    { 8: "pentacles08.jpg" },
    { 9: "pentacles09.jpg" },
    { 10: "pentacles10.jpg" },
    { 11: "pentacles11.jpg" },
    { 12: "pentacles12.jpg" },
    { 13: "pentacles13.jpg" },
    { 14: "pentacles14.jpg" }
  ]
};
